Repository StatusCakeDev/terraform-provider-statuscake, pull requests merged in 2019-06, with the labels that each got.

#34 Add support back for contact_id and mark it as deprecated
  CHANGELOG.md
  statuscake/resource_statuscaketest.go
  statuscake/resource_statuscaketest_test.go
  website/docs/r/test.html.markdown
Labels: documentation, size/M

#35 Add SSL validation feature for uptime tests
  go.mod
  go.sum
  statuscake/resource_statuscaketest.go
  statuscake/resource_statuscaketest_test.go
  vendor/github.com/DreamItGetIT/statuscake/.gitignore
  vendor/github.com/DreamItGetIT/statuscake/.travis.yml
  vendor/github.com/DreamItGetIT/statuscake/Gopkg.lock
  vendor/github.com/DreamItGetIT/statuscake/Gopkg.toml
  vendor/github.com/DreamItGetIT/statuscake/README.md
  vendor/github.com/DreamItGetIT/statuscake/doc.go
  vendor/github.com/DreamItGetIT/statuscake/makefile
  vendor/github.com/DreamItGetIT/statuscake/responses.go
  vendor/github.com/DreamItGetIT/statuscake/tests.go
  vendor/modules.txt
  website/docs/r/test.html.markdown
Labels: dependencies, documentation, size/L

#36 Add importer
  statuscake/resource_statuscaketest.go
  website/docs/r/test.html.markdown
Labels: documentation, size/XS

#39 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS
